Repository ProyectoIntegrador2018/conexion_tec, pull requests merged in 2019-10, with the labels that each got.

#202 Add Edition valididations when registering or editing projects as student
  app/views/student/projects/_project.html.erb
  app/views/student/projects/index.html.erb
Labels: Ruby O's, Sprint2

#203 Feature/abstract grades implementation
  app/controllers/common/project_grades_controller.rb
  app/models/project_grade.rb
  app/views/common/project_grades/_form.html.erb
  app/views/common/project_grades/new.html.erb
  app/views/common/projects/_form.html.erb
  app/views/student/projects/_form.html.erb
  db/migrate/20191008020515_remove_grades_from_project_grades.rb
  db/migrate/20191008020814_add_grades_to_project_grades.rb
  db/schema.rb
Labels: Ruby O's, Sprint2

#205 Fix indentation issues and modify sort_by functions to ignore case
  app/controllers/common/assignments_controller.rb
  app/controllers/common/projects_assistance_controller.rb
  app/controllers/common/projects_controller.rb
  app/controllers/common/stands_assignment_controller.rb
  app/controllers/judge/projects_controller.rb
  app/controllers/student/projects_controller.rb
Labels: Ruby O's, Sprint2

#213 Fix/project assistance
  app/controllers/common/judges_assistance_controller.rb
  app/controllers/common/projects_assistance_controller.rb
  app/helpers/attendance_helper.rb
  app/models/project.rb
  db/seeds.rb
Labels: Ruby O's

#212 Fix pr template
  pull_request_template.md
Labels: Ruby O's

#216 Feature/social impact forms
  app/assets/javascripts/students.coffee
  app/controllers/common/projects_controller.rb
  app/controllers/student/projects_controller.rb
  app/models/project.rb
  app/views/common/projects/_form.html.erb
  app/views/common/projects/new.html.erb
  app/views/student/projects/_form.html.erb
  app/views/student/projects/edit.html.erb
  app/views/student/projects/new.html.erb
  db/migrate/20191017221053_add_social_impact_fields_to_project.rb
  db/schema.rb
Labels: Ruby O's, Sprint2

#219 Feature/professor approve project
  app/controllers/common/assignments_controller.rb
  app/controllers/common/projects_controller.rb
  app/controllers/professor/projects_controller.rb
  app/controllers/student/projects_controller.rb
  app/models/project.rb
  app/models/status.rb
  app/views/professor/projects/_project.html.erb
  app/views/professor/projects/index.html.erb
  config/routes.rb
  db/seeds.rb
Labels: Ruby O's, Sprint2

#221 Feature/projects sorted by grade
  app/assets/stylesheets/application.scss
  app/controllers/common/projects_controller.rb
  app/helpers/common/projects_helper.rb
  app/views/common/projects/_project.html.erb
  app/views/common/projects/index.html.erb
Labels: Ruby O's, Sprint2

#222 Bug/update project status
  app/controllers/common/project_grades_controller.rb
Labels: Ruby O's, Sprint2, bug
